name: Build and Test ICU4C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # x86-64 Build Job
  build-library-linux-x86-64:
    name: Build (Linux x86-64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Build on x86-64
        run: |
          chmod +x *.sh
          mkdir -p build
          mkdir -p dist

          echo "Ensure build environment ..."
          sudo ./ensure-linux-x86-build-environment.sh

          echo "Build ..."
          ./build-linux-x86-64.sh
            
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-linux-x86-64
          path: dist/fmt-*_linux-x86-64_*.zip
          if-no-files-found: error
          retention-days: 1

  # x86-64 Build Test Job
  build-test-linux-x86-64:
    name: Build Test (Linux x86-64)
    needs: build-library-linux-x86-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-x86-64
          path: dist

      - name: Run on x86-64
        run: |
            # Install minimal dependencies for testing
            sudo apt-get update
            sudo apt-get install -y      \
              build-essential            \
              gnupg                      \
              lsb-release                \
              unzip                      \
              wget                       \
              2>&1 | grep -E 'is already the newest version|Setting up|Preparing to unpack|Installing'

            sudo ./ensure-linux-llvm-setup.sh

            DIST_FILE=$(find dist -name 'fmt-*_linux-x86-64_*.zip' -type f)

            cd tests
            ./build-simple-test-linux-x86-64.sh "../$DIST_FILE"

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-linux-x86-64-test
          path: tests/simple-test
          if-no-files-found: error
          retention-days: 1

  # x86-64 Run Test Job
  run-test-linux-x86-64:
    name: Run Test (Linux x86-64)
    needs: build-test-linux-x86-64
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-x86-64-test

      - name: Run test
        run: |
            chmod +x simple-test
            ./simple-test


  # ARM-64 Build Job
  build-library-linux-arm-64:
    name: Build (Linux ARM-64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Run on ARM-64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            chmod +x *.sh
            mkdir -p build
            mkdir -p dist

            echo "Ensure build environment ..."
            ./ensure-linux-arm-build-environment.sh

            echo "Build ..."
            ./build-linux-arm-64.sh
            
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-linux-arm-64
          path: dist/fmt-*_linux-arm-64_*.zip
          if-no-files-found: error
          retention-days: 1

  # ARM-64 Build Test Job
  build-test-linux-arm-64:
    name: Build Test (Linux ARM-64)
    needs: build-library-linux-arm-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-arm-64
          path: dist

      - name: Run on ARM-64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            # Set environment variables
            export CLANG_VERSION=20

            # Install minimal dependencies for testing
            apt-get update
            apt-get install -y           \
              build-essential            \
              cmake                      \
              curl                       \
              gnupg                      \
              lsb-release                \
              software-properties-common \
              pkg-config                 \
              unzip                      \
              wget                       \
              2>&1 | grep -E 'is already the newest version|Setting up|Preparing to unpack|Installing'
            
            ./ensure-linux-llvm-setup.sh

            DIST_FILE=$(find dist -name 'fmt-*_linux-arm-64_*.zip' -type f)

            cd tests
            ./build-simple-test-linux-arm-64.sh "../$DIST_FILE"

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-linux-arm-64-test
          path: tests/simple-test
          if-no-files-found: error
          retention-days: 1

  # ARM-64 Run Test Job
  run-test-linux-arm-64:
    name: Run Test (Linux ARM-64)
    needs: build-test-linux-arm-64
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-arm-64-test

      - name: Install dependencies
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            chmod +x simple-test
            ./simple-test

  # Windows Build Job
  build-library-windows-x86-64:
    name: Build (Windows x86-64)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Windows build environment
        shell: pwsh
        run: |
          # Create build directories
          New-Item -ItemType Directory -Path build -Force | Out-Null
          New-Item -ItemType Directory -Path dist -Force | Out-Null
          .\Ensure-WindowsBuildEnvironment.ps1

          .\Build-Windows-x86-64.ps1
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-windows-x86-64
          path: dist/fmt-*_windows-x86-64_*.zip
          if-no-files-found: warn
          retention-days: 1

  # Windows x86-64 Build Test Job
  build-test-windows-x86-64:
    name: Build Test (Windows x86-64)
    needs: build-library-windows-x86-64
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: fmt-windows-x86-64
        path: dist

    - name: Enable UTF-8 and allow script execution
      run: |
        chcp 65001
        Set-ExecutionPolicy Bypass -Scope Process -Force

    - name: Build test executable
      shell: pwsh
      run: |
        cd tests
        $distFile = Get-ChildItem -Path "../dist" -Filter "fmt-*_windows-x86-64_*.zip" -Recurse | Select-Object -ExpandProperty FullName
        ./Build-SimpleTest-windows-x86-64.ps1 $distFile

    - name: Upload test binary
      uses: actions/upload-artifact@v4
      with:
        name: fmt-windows-x86-64-test
        path: tests/simple-test-x86-64.exe

  run-test-windows-x86-64:
    name: Run Test (Windows x86-64)
    needs: build-test-windows-x86-64
    runs-on: windows-latest

    steps:
      - name: Download test binary
        uses: actions/download-artifact@v4
        with:
          name: fmt-windows-x86-64-test

      - name: Run test
        run: .\simple-test-x86-64.exe
        shell: cmd

  # # Windows Build Job
  # build-library-windows-arm-64:
  #   name: Build (Windows arm)
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Setup Windows build environment
  #       shell: pwsh
  #       run: |
  #         # Create build directories
  #         New-Item -ItemType Directory -Path build -Force | Out-Null
  #         New-Item -ItemType Directory -Path dist -Force | Out-Null
  #         .\Ensure-WindowsBuildEnvironment.ps1

  #         .\Build-Windows-arm-64.ps1
      
  #     - name: Upload build artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: fmt-windows-arm-64
  #         path: dist/fmt-*_windows-arm-64_*.zip
  #         if-no-files-found: warn
  #         retention-days: 1

  # # Windows ARM64 Build Test Job
  # build-test-windows-arm-64:
  #   name: Build Test (Windows ARM64)
  #   needs: build-library-windows-arm-64
  #   runs-on: windows-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Download build artifact
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: fmt-windows-arm-64
  #       path: dist

  #   - name: Enable UTF-8 and allow script execution
  #     run: |
  #       chcp 65001
  #       Set-ExecutionPolicy Bypass -Scope Process -Force

  #   - name: Build test executable for ARM64
  #     shell: pwsh
  #     run: |
  #       cd tests
  #       $distFile = Get-ChildItem -Path "../dist" -Filter "fmt-*_windows-arm-64_*.zip" -Recurse | Select-Object -ExpandProperty FullName
  #       ./Build-SimpleTest-windows-arm-64.ps1 $distFile

  #   - name: Upload test binary
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: fmt-windows-arm-64-test
  #       path: tests/simple-test-arm64.exe


  # run-test-windows-arm-64:
  #   name: Run Test (Windows ARM64)
  #   needs: build-test-windows-arm-64
  #   runs-on: windows-11-arm

  #   steps:
  #     - name: Download test binary
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: fmt-windows-arm-64-test

  #     - name: Run test
  #       run: .\simple-test-arm-64.exe
  #       shell: cmd

  # macOS Universal Build Job
  build-library-macos-universal:
    name: Build (macOS Universal)
    runs-on: macos-13 # or macos-14 if using latest Xcode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'HOMEBREW_NO_AUTO_UPDATE=1' >> $GITHUB_ENV

      - name: Make scripts executable
        run: chmod +x *.sh sh-sources/*.sh

      - name: Build macOS Universal binary
        run: |
          source ensure-macos-build-environment.sh

          brew install llvm@20
          export PATH="/usr/local/opt/llvm@20/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/llvm@20/lib"
          export CPPFLAGS="-I/usr/local/opt/llvm@20/include"
          
          echo "=== Compiler Information ==="
          echo "which clang      : $(which clang)"
          echo "which clang++    : $(which clang++)"
          echo "which llvm-ar    : $(which llvm-ar)"
          echo "which llvm-ranlib: $(which llvm-ranlib)"
          clang --version
          clang++ --version
          llvm-ar --version
          llvm-ranlib --version

          ./build-macos-universal.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-macos-universal
          path: dist/fmt-*_macos-universal_*.zip
          if-no-files-found: error
          retention-days: 1
  
  build-test-macos-universal:
    name: Build Test (macOS Universal)
    needs: build-library-macos-universal
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'HOMEBREW_NO_AUTO_UPDATE=1' >> $GITHUB_ENV

      - name: Make scripts executable
        run: chmod +x *.sh sh-sources/*.sh tests/*.sh

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-macos-universal
          path: dist
      
      - name: Ensure macOS build environment
        run: |
          ./ensure-macos-build-environment.sh

      - name: Run macOS Universal test build
        run: |
          DIST_FILE=$(find dist -name 'fmt-*_macos-universal_*.zip' -type f)
          cd tests
          ./build-simple-test-macos-universal.sh "../$DIST_FILE"

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-macos-universal-test
          path: tests/simple-test
          if-no-files-found: error
          retention-days: 1

  run-test-macos-x86-64:
    name: Run Test (macOS x86-64)
    needs: build-test-macos-universal
    runs-on: macos-13

    steps:
      - name: Download test binary
        uses: actions/download-artifact@v4
        with:
          name: fmt-macos-universal-test

      - name: Make test executable
        run: chmod +x simple-test

      - name: Run test
        run: ./simple-test
        shell: bash

  run-test-macos-arm-64:
    name: Run Test (macOS arm-64)
    needs: build-test-macos-universal
    runs-on: macos-14

    steps:
      - name: Download test binary
        uses: actions/download-artifact@v4
        with:
          name: fmt-macos-universal-test

      - name: Make test executable
        run: chmod +x simple-test

      - name: Run test
        run: ./simple-test
        shell: bash
  
  # Combine Libraries Job
  combine-libraries:
    name: Combine Libraries
    runs-on: ubuntu-latest
    needs: 
      - build-library-linux-x86-64
      - build-library-linux-arm-64
      - build-library-windows-x86-64
      - build-library-macos-universal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-x86-64
          path: build/build-linux-x86-64

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-arm-64
          path: build/build-linux-arm-64

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-windows-x86-64
          path: build/build-windows-x86-64  

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-macos-universal
          path: build/build-macos-universal

      - name: Show downloaded files
        run: |
          sudo apt-get update
          sudo apt-get -y install tree
          echo "Current directory:"
          pwd
          echo "Top-level contents:"
          ls -la
          echo "Move to combine directory"
          mv build combine/
          echo "Downloaded build artifacts:"
          tree combine/build
          echo "Combining libraries..."
          cd combine
          chmod +x ./combine-library.sh
          ./combine-library.sh ../versions.env

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-combined
          path: combine/fmt-*.zip
          if-no-files-found: error
          retention-days: 1
