name: Build and Test ICU4C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # x86-64 Build Job
  build-x86-64:
    name: Build (Linux x86-64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Run on x86-64
        run: |




            # Set environment variables
            export CLANG_VERSION=20

            # Install dependencies
            sudo apt-get update
            sudo apt-get install -y      \
              build-essential            \
              cmake                      \
              curl                       \
              pkg-config                 \
              unzip                      \
              wget                       \
              zip
            
            # Install LLVM/Clang
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh || true
            sudo ./llvm.sh ${CLANG_VERSION}
            rm llvm.sh




            # Create symlinks for clang and LLVM tools to be available without version suffix
            sudo update-alternatives --install /usr/bin/clang   clang   /usr/bin/clang-${CLANG_VERSION}   100
            sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_VERSION} 100
            sudo update-alternatives --set                      clang   /usr/bin/clang-${CLANG_VERSION}
            sudo update-alternatives --set                      clang++ /usr/bin/clang++-${CLANG_VERSION}
            sudo ln -sf /usr/bin/llvm-ar-${CLANG_VERSION} /usr/bin/llvm-ar
            sudo ln -sf /usr/bin/llvm-ranlib-${CLANG_VERSION} /usr/bin/llvm-ranlib
            
            echo "Setup LLVM/Clang"
            echo "Clang       version: "$(clang   --version)
            echo "Clang++     version: "$(clang++ --version)
            echo "LLVM-ar     version: "$(llvm-ar-${CLANG_VERSION}     --version)
            echo "LLVM-ranlib version: "$(llvm-ranlib-${CLANG_VERSION} --version)
            
            echo "Build ..."
            ./build-linux-x86-64.sh
            pwd
            ls -ls dist
            
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-linux-x86-64
          path: dist/fmt-*_linux-x86-64_*.zip
          if-no-files-found: error
          retention-days: 1

  # x86-64 Build Test Job
  build-test-x86-64:
    name: Build Test (Linux x86-64)
    needs: build-x86-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-x86-64
          path: dist

      - name: Run on x86-64
        run: |


            # Set environment variables
            export CLANG_VERSION=20

            # Install minimal dependencies for testing
            sudo apt-get update
            sudo apt-get install -y      \
              build-essential            \
              unzip                      \
              wget


            
            # Install LLVM/Clang
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh || true
            sudo ./llvm.sh ${CLANG_VERSION}
            rm llvm.sh




            # Create symlinks for clang and LLVM tools to be available without version suffix
            sudo update-alternatives --install /usr/bin/clang   clang   /usr/bin/clang-${CLANG_VERSION}   100
            sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_VERSION} 100
            sudo update-alternatives --set                      clang   /usr/bin/clang-${CLANG_VERSION}
            sudo update-alternatives --set                      clang++ /usr/bin/clang++-${CLANG_VERSION}
            sudo ln -sf /usr/bin/llvm-ar-${CLANG_VERSION} /usr/bin/llvm-ar
            sudo ln -sf /usr/bin/llvm-ranlib-${CLANG_VERSION} /usr/bin/llvm-ranlib

            echo "Setup LLVM/Clang"
            echo "Clang       version: "$(clang   --version)
            echo "Clang++     version: "$(clang++ --version)
            echo "LLVM-ar     version: "$(llvm-ar-${CLANG_VERSION}     --version)
            echo "LLVM-ranlib version: "$(llvm-ranlib-${CLANG_VERSION} --version)

            mkdir -p tests/build
            DIST_FILE=$(find dist -name 'fmt-*_linux-x86-64_*.zip' -type f)
            unzip -o "$DIST_FILE" -d tests/build

            cd tests
            ./build-simple-test-linux-x86-64.sh "../$DIST_FILE"

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-linux-x86-64-test
          path: tests/simple-test
          if-no-files-found: error
          retention-days: 1

  # x86-64 Run Test Job
  run-test-x86-64:
    name: Run Test (Linux x86-64)
    needs: build-test-x86-64
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-x86-64-test

      - name: Run test
        run: |
            chmod +x simple-test
            ./simple-test


  # ARM-64 Build Job
  build-arm-64:
    name: Build (Linux ARM-64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Run on ARM-64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            # Set environment variables
            export CLANG_VERSION=20

            # Install dependencies
            apt-get update
            apt-get install -y           \
              build-essential            \
              cmake                      \
              curl                       \
              lsb-release                \
              pkg-config                 \
              software-properties-common \
              unzip                      \
              wget                       \
              zip
            

            # Install LLVM/Clang
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh || true
            ./llvm.sh ${CLANG_VERSION}
            rm llvm.sh


            # Create symlinks for clang and LLVM tools to be available without version suffix
            update-alternatives --install /usr/bin/clang   clang   /usr/bin/clang-${CLANG_VERSION}   100
            update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_VERSION} 100
            update-alternatives --set                      clang   /usr/bin/clang-${CLANG_VERSION}
            update-alternatives --set                      clang++ /usr/bin/clang++-${CLANG_VERSION}
            ln -sf /usr/bin/llvm-ar-${CLANG_VERSION} /usr/bin/llvm-ar
            ln -sf /usr/bin/llvm-ranlib-${CLANG_VERSION} /usr/bin/llvm-ranlib
            
            echo "Setup LLVM/Clang"
            echo "Clang       version: "$(clang   --version)
            echo "Clang++     version: "$(clang++ --version)
            echo "LLVM-ar     version: "$(llvm-ar-${CLANG_VERSION}     --version)
            echo "LLVM-ranlib version: "$(llvm-ranlib-${CLANG_VERSION} --version)
            
            echo "Build ..."
            ./build-linux-arm-64.sh
            
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-linux-arm-64
          path: dist/fmt-*_linux-arm-64_*.zip
          if-no-files-found: error
          retention-days: 1

  # ARM-64 Build Test Job
  build-test-arm-64:
    name: Build Test (Linux ARM-64)
    needs: build-arm-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-arm-64
          path: dist

      - name: Run on ARM-64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            # Set environment variables
            export CLANG_VERSION=20

            # Install minimal dependencies for testing
            apt-get update
            apt-get install -y \
              build-essential  \
              cmake            \
              curl             \
              gnupg            \
              pkg-config       \
              unzip            \
              wget             \
              zip

            
            # Install LLVM/Clang
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh || true
            ./llvm.sh ${CLANG_VERSION}
            rm llvm.sh


            # Create symlinks for clang and LLVM tools to be available without version suffix
            update-alternatives --install /usr/bin/clang   clang   /usr/bin/clang-${CLANG_VERSION}   100
            update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_VERSION} 100
            update-alternatives --set                      clang   /usr/bin/clang-${CLANG_VERSION}
            update-alternatives --set                      clang++ /usr/bin/clang++-${CLANG_VERSION}
            ln -sf /usr/bin/llvm-ar-${CLANG_VERSION} /usr/bin/llvm-ar
            ln -sf /usr/bin/llvm-ranlib-${CLANG_VERSION} /usr/bin/llvm-ranlib

            echo "Setup LLVM/Clang"
            echo "Clang       version: "$(clang   --version)
            echo "Clang++     version: "$(clang++ --version)
            echo "LLVM-ar     version: "$(llvm-ar-${CLANG_VERSION}     --version)
            echo "LLVM-ranlib version: "$(llvm-ranlib-${CLANG_VERSION} --version)

            mkdir -p tests/build
            DIST_FILE=$(find dist -name 'fmt-*_linux-arm-64_*.zip' -type f)
            unzip -o "$DIST_FILE" -d tests/build

            cd tests
            ./build-simple-test-linux-arm-64.sh "../$DIST_FILE"

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmt-linux-arm-64-test
          path: tests/simple-test
          if-no-files-found: error
          retention-days: 1

  # ARM-64 Run Test Job
  run-test-arm-64:
    name: Run Test (Linux ARM-64)
    needs: build-test-arm-64
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fmt-linux-arm-64-test

      - name: Install dependencies
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            chmod +x simple-test
            ./simple-test
